---
version: "2"
plugins:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  csslint:
    enabled: true
#  structure:
#    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 80
  eslint:
    enabled: true
    config:
      config: .eslintrc.yml
  fixme:
    enabled: true
exclude_patterns:
- test/
- node_modules/
- bower_components/
#ratings:
#  paths:
#  - "**.css"
#  - "**.js"
#  - "**.go"
