version: 1.0.{build}
image:
  - Ubuntu
environment:
  matrix:
    - ARCH: amd64
  DOCKER_USER:
    secure: JapmC7j5F0mY3j/MVzU+Cw==
  DOCKER_PASS:
    secure: QGlCLNWzPD0HL8ipkohVic45/yU3bVOdjn0IiV6NnSQ=
  IMAGE: linux
branches:
  only:
    - develop
stack: node 9
install:
  - yarn install
build_script:
  - sh: yarn grunt release:$IMAGE:$ARCH
  - sh: sudo bash build/build_container_image.sh $IMAGE $ARCH $PORTAINER_VERSION $DOCKER_USER $DOCKER_PASS '' $APPVEYOR_PULL_REQUEST_NUMBER
notifications:
  - provider: GitHubPullRequest
    auth_token:
      secure: yC+WkZ45ZI6a4adDsjJS71L9GvbPLjTC9Q1QpTQdsqVlBb6DjEPYg6NuJ79nNFeh
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) Test the image ssbkang/portainer:pr$APPVEYOR_PULL_REQUEST_NUMBER (commit {{commitUrl}} by @{{&commitAuthorUsername}})"