version: 1.0.{build}
image:
  - Visual Studio 2017
  - Ubuntu
environment:
  matrix:
    - ARCH: amd64
    #- ARCH: arm 
    #- ARCH: arm64
    #- ARCH: ppc64le
    #- ARCH: s390x
  DOCKER_HUB_USERNAME:
    secure: JapmC7j5F0mY3j/MVzU+Cw==
  DOCKER_HUB_PASSWORD:
    secure: QGlCLNWzPD0HL8ipkohVic45/yU3bVOdjn0IiV6NnSQ=
  PORTAINER_VERSION: "1.19.2"
matrix:
  exclude:
    - image: Visual Studio 2017
      ARCH: arm
    - image: Visual Studio 2017
      ARCH: arm64
    - image: Visual Studio 2017
      ARCH: ppc64le
    - image: Visual Studio 2017
      ARCH: s390x
branches:
  only:
    - master
stack: node 9
install:
  - yarn install
  - npm install -g rebase-docker-image
init:
  - echo $APPVEYOR_PULL_REQUEST_NUMBER
  - echo $APPVEYOR_REPO_BRANCH
  - echo $APPVEYOR_REPO_COMMIT
build_script:
  - ps: if ($isLinux) { Set-Item ENV:IMAGE -Value 'linux'; sh -c 'yarn grunt release:$IMAGE:$ARCH' } else { Set-Item ENV:IMAGE -Value 'windows' }
  - cmd: yarn grunt release:%IMAGE%:%ARCH%
  - ps: |
      if ($isLinux) { $dockerfile_path = "build/linux/Dockerfile" } else { $dockerfile_path = "build\windows2016\nanoserver\Dockerfile" }

      docker build -t ssbkang/portainer:$((Get-Item ENV:IMAGE).Value)-$((Get-Item ENV:ARCH).Value)-$((Get-Item ENV:PORTAINER_VERSION).Value) -f "$($dockerfile_path)" .
      docker tag ssbkang/portainer:$((Get-Item ENV:IMAGE).Value)-$((Get-Item ENV:ARCH).Value)-$((Get-Item ENV:PORTAINER_VERSION).Value) ssbkang/portainer:$((Get-Item ENV:IMAGE).Value)-$((Get-Item ENV:ARCH).Value)
      docker login -u "$((Get-Item ENV:DOCKER_HUB_USERNAME).Value)" -p "$((Get-Item ENV:DOCKER_HUB_PASSWORD).Value)"
      docker push ssbkang/portainer:$((Get-Item ENV:IMAGE).Value)-$((Get-Item ENV:ARCH).Value)-$((Get-Item ENV:PORTAINER_VERSION).Value)
      docker push ssbkang/portainer:$((Get-Item ENV:IMAGE).Value)-$((Get-Item ENV:ARCH).Value)

      if ($isWindows) { 
        rebase-docker-image ssbkang/portainer:$((Get-Item ENV:IMAGE).Value)-$((Get-Item ENV:ARCH).Value) -t ssbkang/portainer:$((Get-Item ENV:IMAGE).Value)1709-$((Get-Item ENV:ARCH).Value)-$((Get-Item ENV:PORTAINER_VERSION).Value) -b microsoft/nanoserver:1709
        rebase-docker-image ssbkang/portainer:$((Get-Item ENV:IMAGE).Value)-$((Get-Item ENV:ARCH).Value) -t ssbkang/portainer:$((Get-Item ENV:IMAGE).Value)1803-$((Get-Item ENV:ARCH).Value)-$((Get-Item ENV:PORTAINER_VERSION).Value) -b microsoft/nanoserver:1803
      }
