version: 1.0.{build}
image:
  - Visual Studio 2017
  - Ubuntu1804
environment:	
  matrix:	
    - ARCH: amd64
branches:
  only:
    - master
install:
  - ps: 'Install-Product node $env:node_version'
  - yarn install
build_script:
  - yarn grunt release:windows:amd64
