environment:
  matrix:
    - node_version: '10'
branches:
  only:
    - master
install:
  - ps: 'Install-Product node $env:node_version'
  - yarn install
build_script:
  - yarn release:windows:amd64
artifacts:
  - path: ./
    name: dist
