version: 1.0.{build}
image:
  # - Visual Studio 2017
  - Ubuntu
environment:
  matrix:
    - ARCH: amd64
    - ARCH: arm 
    - ARCH: arm64
    - ARCH: ppc64le
    - ARCH: s390x
  NODEJS_VERSION: "8.12.0"
  DOCKER_HUB_USERNAME:
    secure: JapmC7j5F0mY3j/MVzU+Cw==
  DOCKER_HUB_PASSWORD:
    secure: QGlCLNWzPD0HL8ipkohVic45/yU3bVOdjn0IiV6NnSQ=
#matrix:
  #exclude:
  #  - image: Visual Studio 2017
  #    ARCH: arm
  #  - image: Visual Studio 2017
  #    ARCH: arm64
  #  - image: Visual Studio 2017
  #    ARCH: ppc64le
  #  - image: Visual Studio 2017
  #    ARCH: s390x
branches:
  only:
    - master
stack: node 9
install:
  - yarn install
init:
  - echo %APPVEYOR_PULL_REQUEST_NUMBER%
  - echo %APPVEYOR_REPO_BRANCH%
  - ps: if ((Get-Item ENV:APPVEYOR_BUILD_WORKER_IMAGE).Value -eq 'Visual Studio 2017') { Set-Item ENV:image -Value 'windows' } else { Set-Item ENV:image -Value 'linux' }
build_script:
  - echo %image%
  - echo %arch%
  #- yarn grunt release:%image%:%arch%
#deploy_script:
# 
#  - docker build -t ssbkang/portainer:develop-windows -f "build\windows2016\nanoserver\Dockerfile" .
#  - docker login -u "%DOCKER_HUB_USERNAME%" -p "%DOCKER_HUB_PASSWORD%"
#  - docker push ssbkang/portainer:develop-windows