version: 1.0.{build}
image:
  - Visual Studio 2017
environment:	
  matrix:	
    - ARCH: amd64
branches:
  only:
    - master
install:
  - yarn install
build_script:
  - yarn grunt release:windows:amd64
