version: 1.0.{build}
image:
  - Visual Studio 2017
  #- Ubuntu
environment:
  matrix:
    - ARCH: amd64
    - ARCH: arm 
    - ARCH: arm64
    - ARCH: ppc64le
    - ARCH: s390x
  DOCKER_USER:
    secure: JapmC7j5F0mY3j/MVzU+Cw==
  DOCKER_PASS:
    secure: QGlCLNWzPD0HL8ipkohVic45/yU3bVOdjn0IiV6NnSQ=
  GITHUB_TOKEN:
    secure: yC+WkZ45ZI6a4adDsjJS71L9GvbPLjTC9Q1QpTQdsqVlBb6DjEPYg6NuJ79nNFeh
  PORTAINER_VERSION: "1.19.2"
matrix:
  exclude:
    - image: Visual Studio 2017
      ARCH: arm
    - image: Visual Studio 2017
      ARCH: arm64
    - image: Visual Studio 2017
      ARCH: ppc64le
    - image: Visual Studio 2017
      ARCH: s390x
branches:
  only:
    - master
stack: node 9
install:
  - yarn install
  - npm install -g rebase-docker-image
init:
  - ps: if ($isLinux) { Set-Item ENV:IMAGE -Value 'linux' } else { Set-Item ENV:IMAGE -Value 'windows' }
build_script:
  - sh: yarn grunt release:$IMAGE:$ARCH
  - cmd: yarn grunt release:%IMAGE%:%ARCH%
  - sh: sudo bash build/build_container_image.sh
  - cmd: 'powershell -Command "& .\\build\\build_container_image.ps1"'