version: 1.0.{build}
image:
  - Visual Studio 2017
environment:
  DOCKER_HUB_USERNAME:
    secure: JapmC7j5F0mY3j/MVzU+Cw==
  DOCKER_HUB_PASSWORD:
    secure: QGlCLNWzPD0HL8ipkohVic45/yU3bVOdjn0IiV6NnSQ=
  matrix:
    - ARCH: amd64
branches:
  only:
    - master
install:
  - yarn install
build_script:
  - yarn grunt release:windows:amd64
  - docker build -t ssbkang/portainer:develop-windows -f "build\windows2016\nanoserver\Dockerfile" .
deploy_script:
  - docker image ls
  - docker login -u "$env:DOCKER_HUB_USERNAME" -p "$env:DOCKER_HUB_PASSWORD"
  - docker push ssbkang/portainer:develop-windows
